{{- if .Values.api.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "anvilops.fullname" . }}-api
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "anvilops.componentLabels" (list . "api") | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      {{- include "anvilops.componentSelectorLabels" (list . "api") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "anvilops.componentLabels" (list . "api") | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.api.serviceAccount.name }}
      securityContext:
        runAsNonRoot: true
        runAsUser: {{ .Values.api.podSecurityContext.runAsUser }}
        runAsGroup: {{ .Values.api.podSecurityContext.runAsGroup }}
        fsGroup: {{ .Values.api.podSecurityContext.fsGroup }}
        seccompProfile:
          type: RuntimeDefault
      {{- if .Values.api.topologySpreadConstraints.enabled }}
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              {{- include "anvilops.componentSelectorLabels" (list . "api") | nindent 14 }}
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              {{- include "anvilops.componentSelectorLabels" (list . "api") | nindent 14 }}
      {{- end }}
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.api.service.targetPort }}
              name: http
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "anvilops.fullname" . }}-config
            {{- if .Values.externalSecrets.enabled }}
            - secretRef:
                name: {{ include "anvilops.fullname" . }}-api-secrets
            - secretRef:
                name: {{ include "anvilops.fullname" . }}-shared-secrets
            {{- end }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          securityContext:
            {{- include "anvilops.containerSecurityContext" . | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          startupProbe:
            {{- toYaml .Values.api.probes.startup | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.api.probes.readiness | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.api.probes.liveness | nindent 12 }}
      volumes:
        - name: tmp
          emptyDir:
            sizeLimit: 1Gi
      restartPolicy: Always
{{- end }}
