apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "anvilops.fullname" . }}-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "anvilops.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
