{{- if and .Values.api.enabled .Values.api.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "anvilops.fullname" . }}-api-pdb
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "anvilops.componentLabels" (list . "api") | nindent 4 }}
spec:
  minAvailable: {{ .Values.api.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "anvilops.componentSelectorLabels" (list . "api") | nindent 6 }}
{{- end }}
{{- if and .Values.worker.enabled .Values.worker.pdb.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "anvilops.fullname" . }}-worker-pdb
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "anvilops.componentLabels" (list . "worker") | nindent 4 }}
spec:
  minAvailable: {{ .Values.worker.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "anvilops.componentSelectorLabels" (list . "worker") | nindent 6 }}
{{- end }}
{{- if and .Values.frontend.enabled .Values.frontend.pdb.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "anvilops.fullname" . }}-frontend-pdb
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "anvilops.componentLabels" (list . "frontend") | nindent 4 }}
spec:
  minAvailable: {{ .Values.frontend.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "anvilops.componentSelectorLabels" (list . "frontend") | nindent 6 }}
{{- end }}
