apiVersion: v1
kind: Service
metadata:
  name: anvilops-frontend
  namespace: anvilops
  labels:
    app.kubernetes.io/name: anvilops-frontend
    app.kubernetes.io/part-of: anvilops
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: anvilops-frontend
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
