apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: anvilops-ingress
  namespace: anvilops
  labels:
    app.kubernetes.io/part-of: anvilops
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: "REPLACE_WITH_ACM_CERT_ARN"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/healthcheck-path: /api/v1/health
    alb.ingress.kubernetes.io/group.name: anvilops
    alb.ingress.kubernetes.io/tags: Environment=dev,Application=anvilops
spec:
  ingressClassName: alb
  rules:
    - host: anvilops.example.com
      http:
        paths:
          - path: /api/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: anvilops-api
                port:
                  number: 80
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: anvilops-frontend
                port:
                  number: 80
