---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: anvilops-api
  namespace: anvilops
  labels:
    app.kubernetes.io/part-of: anvilops
    app.kubernetes.io/component: api
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/anvilops-api-irsa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: anvilops-worker
  namespace: anvilops
  labels:
    app.kubernetes.io/part-of: anvilops
    app.kubernetes.io/component: worker
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/anvilops-worker-irsa
