installCRDs: true

serviceAccount:
  create: true
  name: external-secrets

replicaCount: 2

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 256Mi

webhook:
  replicaCount: 2

certController:
  replicaCount: 1
