grafana:
  enabled: true
  persistence:
    enabled: true
    storageClassName: gp2
    size: 10Gi
  adminPassword: ${grafana_admin_password}
  service:
    type: ClusterIP
  ingress:
    enabled: false

prometheus:
  prometheusSpec:
    retention: 30d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp2
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false

alertmanager:
  enabled: true
  alertmanagerSpec:
    retention: 120h
