"""add_phase_1b_1c_2_3_4_columns

Revision ID: 528e7de10cd8
Revises: e50e8f1b2e9e
Create Date: 2026-02-10 12:11:27.019970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '528e7de10cd8'
down_revision: Union[str, None] = 'e50e8f1b2e9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('actor_role', sa.String(length=30), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('resource_name', sa.String(length=255), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'success'"), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_email'), 'audit_logs', ['actor_email'], unique=False)
    op.create_index(op.f('ix_audit_logs_category'), 'audit_logs', ['category'], unique=False)
    op.create_index('ix_audit_logs_category_action', 'audit_logs', ['category', 'action'], unique=False)
    op.create_index('ix_audit_logs_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index('ix_audit_logs_timestamp_desc', 'audit_logs', [sa.literal_column('timestamp DESC')], unique=False)
    op.create_table('build_schedules',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'active'"), nullable=False),
    sa.Column('schedule_type', sa.String(length=20), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cron_expression', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=50), server_default=sa.text("'UTC'"), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('server_config', sa.JSON(), nullable=False),
    sa.Column('max_runs', sa.Integer(), nullable=True),
    sa.Column('run_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_build_schedules_next_run', 'build_schedules', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_build_schedules_status'), 'build_schedules', ['status'], unique=False)
    op.create_index('ix_build_schedules_status_next_run', 'build_schedules', ['status', 'next_run_at'], unique=False)
    op.create_table('notifications',
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=30), server_default=sa.text("'system'"), nullable=False),
    sa.Column('severity', sa.String(length=20), server_default=sa.text("'info'"), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index('ix_notifications_user_created', 'notifications', ['user_email', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_email'), 'notifications', ['user_email'], unique=False)
    op.create_index('ix_notifications_user_unread', 'notifications', ['user_email', 'is_read'], unique=False)
    op.create_table('scaling_groups',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'active'"), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('os_type', sa.String(length=50), nullable=False),
    sa.Column('instance_size', sa.String(length=20), nullable=False),
    sa.Column('region', sa.String(length=20), nullable=False),
    sa.Column('vpc_id', sa.String(length=50), nullable=False),
    sa.Column('subnet_id', sa.String(length=50), nullable=False),
    sa.Column('security_profile', sa.String(length=20), server_default=sa.text("'internal_only'"), nullable=False),
    sa.Column('puppet_role', sa.String(length=50), server_default=sa.text("'base'"), nullable=False),
    sa.Column('min_instances', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('max_instances', sa.Integer(), server_default=sa.text('5'), nullable=False),
    sa.Column('desired_count', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('current_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('scale_up_threshold', sa.Integer(), server_default=sa.text('80'), nullable=False),
    sa.Column('scale_down_threshold', sa.Integer(), server_default=sa.text('20'), nullable=False),
    sa.Column('cooldown_seconds', sa.Integer(), server_default=sa.text('300'), nullable=False),
    sa.Column('last_scaled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scaling_groups_env_status', 'scaling_groups', ['environment', 'status'], unique=False)
    op.create_index(op.f('ix_scaling_groups_name'), 'scaling_groups', ['name'], unique=True)
    op.create_index(op.f('ix_scaling_groups_status'), 'scaling_groups', ['status'], unique=False)
    op.create_table('server_templates',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), server_default=sa.text("'server'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('os_type', sa.String(length=50), nullable=False),
    sa.Column('instance_size', sa.String(length=20), nullable=False),
    sa.Column('region', sa.String(length=20), server_default=sa.text("'us-east-1'"), nullable=False),
    sa.Column('security_profile', sa.String(length=20), server_default=sa.text("'internal_only'"), nullable=False),
    sa.Column('puppet_role', sa.String(length=50), server_default=sa.text("'base'"), nullable=False),
    sa.Column('domain_join', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('software_packages', sa.JSON(), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('additional_storage', sa.JSON(), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('default_tags', sa.JSON(), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_server_templates_name'), 'server_templates', ['name'], unique=True)
    op.create_table('drift_events',
    sa.Column('server_request_id', sa.Uuid(), nullable=False),
    sa.Column('certname', sa.String(length=255), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_title', sa.String(length=500), nullable=False),
    sa.Column('property_name', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), server_default=sa.text("'medium'"), nullable=False),
    sa.Column('is_corrective', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('resolution_type', sa.String(length=30), nullable=True),
    sa.Column('drift_category', sa.String(length=50), server_default=sa.text("'configuration'"), nullable=False),
    sa.Column('cis_control_id', sa.String(length=20), nullable=True),
    sa.Column('report_hash', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['server_request_id'], ['server_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_drift_events_category', 'drift_events', ['drift_category'], unique=False)
    op.create_index(op.f('ix_drift_events_certname'), 'drift_events', ['certname'], unique=False)
    op.create_index('ix_drift_events_certname_detected', 'drift_events', ['certname', 'detected_at'], unique=False)
    op.create_index(op.f('ix_drift_events_detected_at'), 'drift_events', ['detected_at'], unique=False)
    op.create_index(op.f('ix_drift_events_report_hash'), 'drift_events', ['report_hash'], unique=False)
    op.create_index('ix_drift_events_server_detected', 'drift_events', ['server_request_id', 'detected_at'], unique=False)
    op.create_index(op.f('ix_drift_events_server_request_id'), 'drift_events', ['server_request_id'], unique=False)
    op.create_index('ix_drift_events_severity_resolved', 'drift_events', ['severity', 'is_resolved'], unique=False)
    op.create_table('scaling_group_members',
    sa.Column('scaling_group_id', sa.Uuid(), nullable=False),
    sa.Column('server_request_id', sa.Uuid(), nullable=True),
    sa.Column('member_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'active'"), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scaling_group_id'], ['scaling_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['server_request_id'], ['server_requests.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scaling_group_members_group_index', 'scaling_group_members', ['scaling_group_id', 'member_index'], unique=True)
    op.create_index(op.f('ix_scaling_group_members_scaling_group_id'), 'scaling_group_members', ['scaling_group_id'], unique=False)
    op.create_index(op.f('ix_scaling_group_members_server_request_id'), 'scaling_group_members', ['server_request_id'], unique=False)
    op.create_table('schedule_executions',
    sa.Column('schedule_id', sa.Uuid(), nullable=False),
    sa.Column('server_request_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['build_schedules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['server_request_id'], ['server_requests.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_executions_schedule_id'), 'schedule_executions', ['schedule_id'], unique=False)
    op.create_index('ix_schedule_executions_schedule_status', 'schedule_executions', ['schedule_id', 'status'], unique=False)
    op.create_index(op.f('ix_schedule_executions_status'), 'schedule_executions', ['status'], unique=False)
    op.create_table('drift_alerts',
    sa.Column('drift_event_id', sa.Uuid(), nullable=True),
    sa.Column('server_request_id', sa.Uuid(), nullable=True),
    sa.Column('alert_type', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=20), server_default=sa.text("'medium'"), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_acknowledged', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('acknowledged_by', sa.String(length=255), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['drift_event_id'], ['drift_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['server_request_id'], ['server_requests.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drift_alerts_drift_event_id'), 'drift_alerts', ['drift_event_id'], unique=False)
    op.create_index(op.f('ix_drift_alerts_server_request_id'), 'drift_alerts', ['server_request_id'], unique=False)
    op.create_index('ix_drift_alerts_type_severity', 'drift_alerts', ['alert_type', 'severity'], unique=False)
    op.create_index('ix_drift_alerts_unacknowledged', 'drift_alerts', ['is_acknowledged', 'created_at'], unique=False)
    op.add_column('server_requests', sa.Column('awx_host_id', sa.Integer(), nullable=True))
    op.add_column('server_requests', sa.Column('awx_inventory_id', sa.Integer(), nullable=True))
    op.add_column('server_requests', sa.Column('awx_job_ids', sa.JSON(), nullable=True))
    op.add_column('server_requests', sa.Column('puppet_certname', sa.String(length=256), nullable=True))
    op.add_column('server_requests', sa.Column('puppet_node_group_id', sa.String(length=64), nullable=True))
    op.add_column('server_requests', sa.Column('puppet_last_report_status', sa.String(length=32), nullable=True))
    op.add_column('server_requests', sa.Column('puppet_enrolled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('server_requests', sa.Column('cmdb_sys_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server_requests', 'cmdb_sys_id')
    op.drop_column('server_requests', 'puppet_enrolled_at')
    op.drop_column('server_requests', 'puppet_last_report_status')
    op.drop_column('server_requests', 'puppet_node_group_id')
    op.drop_column('server_requests', 'puppet_certname')
    op.drop_column('server_requests', 'awx_job_ids')
    op.drop_column('server_requests', 'awx_inventory_id')
    op.drop_column('server_requests', 'awx_host_id')
    op.drop_index('ix_drift_alerts_unacknowledged', table_name='drift_alerts')
    op.drop_index('ix_drift_alerts_type_severity', table_name='drift_alerts')
    op.drop_index(op.f('ix_drift_alerts_server_request_id'), table_name='drift_alerts')
    op.drop_index(op.f('ix_drift_alerts_drift_event_id'), table_name='drift_alerts')
    op.drop_table('drift_alerts')
    op.drop_index(op.f('ix_schedule_executions_status'), table_name='schedule_executions')
    op.drop_index('ix_schedule_executions_schedule_status', table_name='schedule_executions')
    op.drop_index(op.f('ix_schedule_executions_schedule_id'), table_name='schedule_executions')
    op.drop_table('schedule_executions')
    op.drop_index(op.f('ix_scaling_group_members_server_request_id'), table_name='scaling_group_members')
    op.drop_index(op.f('ix_scaling_group_members_scaling_group_id'), table_name='scaling_group_members')
    op.drop_index('ix_scaling_group_members_group_index', table_name='scaling_group_members')
    op.drop_table('scaling_group_members')
    op.drop_index('ix_drift_events_severity_resolved', table_name='drift_events')
    op.drop_index(op.f('ix_drift_events_server_request_id'), table_name='drift_events')
    op.drop_index('ix_drift_events_server_detected', table_name='drift_events')
    op.drop_index(op.f('ix_drift_events_report_hash'), table_name='drift_events')
    op.drop_index(op.f('ix_drift_events_detected_at'), table_name='drift_events')
    op.drop_index('ix_drift_events_certname_detected', table_name='drift_events')
    op.drop_index(op.f('ix_drift_events_certname'), table_name='drift_events')
    op.drop_index('ix_drift_events_category', table_name='drift_events')
    op.drop_table('drift_events')
    op.drop_index(op.f('ix_server_templates_name'), table_name='server_templates')
    op.drop_table('server_templates')
    op.drop_index(op.f('ix_scaling_groups_status'), table_name='scaling_groups')
    op.drop_index(op.f('ix_scaling_groups_name'), table_name='scaling_groups')
    op.drop_index('ix_scaling_groups_env_status', table_name='scaling_groups')
    op.drop_table('scaling_groups')
    op.drop_index('ix_notifications_user_unread', table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_email'), table_name='notifications')
    op.drop_index('ix_notifications_user_created', table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_build_schedules_status_next_run', table_name='build_schedules')
    op.drop_index(op.f('ix_build_schedules_status'), table_name='build_schedules')
    op.drop_index('ix_build_schedules_next_run', table_name='build_schedules')
    op.drop_table('build_schedules')
    op.drop_index('ix_audit_logs_timestamp_desc', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_resource', table_name='audit_logs')
    op.drop_index('ix_audit_logs_category_action', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_category'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_email'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
