"""initial

Revision ID: e50e8f1b2e9e
Revises: 
Create Date: 2026-02-06 17:46:41.450649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e50e8f1b2e9e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_requests',
    sa.Column('server_name', sa.String(length=128), nullable=False),
    sa.Column('environment', sa.String(length=32), nullable=False),
    sa.Column('os_type', sa.String(length=64), nullable=False),
    sa.Column('instance_size', sa.String(length=32), nullable=False),
    sa.Column('region', sa.String(length=32), server_default=sa.text("'us-east-1'"), nullable=False),
    sa.Column('vpc_id', sa.String(length=64), nullable=False),
    sa.Column('subnet_id', sa.String(length=64), nullable=False),
    sa.Column('security_profile', sa.String(length=64), server_default=sa.text("'internal_only'"), nullable=False),
    sa.Column('domain_join', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('software_packages', sa.JSON(), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('additional_storage', sa.JSON(), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('tags', sa.JSON(), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('puppet_role', sa.String(length=64), server_default=sa.text("'base'"), nullable=False),
    sa.Column('template_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('status_message', sa.String(length=512), nullable=True),
    sa.Column('aws_instance_id', sa.String(length=64), nullable=True),
    sa.Column('private_ip', sa.String(length=45), nullable=True),
    sa.Column('public_ip', sa.String(length=45), nullable=True),
    sa.Column('dns_name', sa.String(length=256), nullable=True),
    sa.Column('terraform_workspace', sa.String(length=128), nullable=True),
    sa.Column('terraform_state_key', sa.String(length=256), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_server_requests_env_status', 'server_requests', ['environment', 'status'], unique=False)
    op.create_index(op.f('ix_server_requests_environment'), 'server_requests', ['environment'], unique=False)
    op.create_index(op.f('ix_server_requests_server_name'), 'server_requests', ['server_name'], unique=True)
    op.create_index(op.f('ix_server_requests_status'), 'server_requests', ['status'], unique=False)
    op.create_table('build_steps',
    sa.Column('server_request_id', sa.Uuid(), nullable=False),
    sa.Column('step_name', sa.String(length=64), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('output_log', sa.Text(), nullable=True),
    sa.Column('error_message', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['server_request_id'], ['server_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_build_steps_request_order', 'build_steps', ['server_request_id', 'step_order'], unique=True)
    op.create_index(op.f('ix_build_steps_server_request_id'), 'build_steps', ['server_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_build_steps_server_request_id'), table_name='build_steps')
    op.drop_index('ix_build_steps_request_order', table_name='build_steps')
    op.drop_table('build_steps')
    op.drop_index(op.f('ix_server_requests_status'), table_name='server_requests')
    op.drop_index(op.f('ix_server_requests_server_name'), table_name='server_requests')
    op.drop_index(op.f('ix_server_requests_environment'), table_name='server_requests')
    op.drop_index('ix_server_requests_env_status', table_name='server_requests')
    op.drop_table('server_requests')
    # ### end Alembic commands ###
