# =============================================================================
# AnvilOps Server Provisioning Variables - Dev Environment
# =============================================================================
# These variables map directly to the server builder form in the AnvilOps UI.
# The API generates a .tfvars file from each build request.
#
# Environment-specific defaults: environment="dev", instance_size="small".
# All other defaults and validations live in the shared module.
# =============================================================================

# -----------------------------------------------------------------------------
# Server Identity
# -----------------------------------------------------------------------------

variable "server_name" {
  description = "Name of the server (e.g., DEV-WEB-a3f8). Auto-generated by the API in ENV-ROLE-RANDOM format."
  type        = string
}

variable "environment" {
  description = "Deployment environment."
  type        = string
  default     = "dev"

  validation {
    condition     = contains(["dev", "staging", "production"], var.environment)
    error_message = "Environment must be one of: dev, staging, production."
  }
}

variable "os_type" {
  description = "Operating system type: windows_2022, windows_2019, amazon_linux_2023, ubuntu_2204, rhel_9."
  type        = string

  validation {
    condition     = contains(["windows_2022", "windows_2019", "amazon_linux_2023", "ubuntu_2204", "rhel_9"], var.os_type)
    error_message = "OS type must be one of: windows_2022, windows_2019, amazon_linux_2023, ubuntu_2204, rhel_9."
  }
}

variable "instance_size" {
  description = "Server size: small (2 vCPU/4GB), medium (4/16), large (8/32), xl (16/64)."
  type        = string
  default     = "small"

  validation {
    condition     = contains(["small", "medium", "large", "xl"], var.instance_size)
    error_message = "Instance size must be one of: small, medium, large, xl."
  }
}

variable "region" {
  description = "AWS region to deploy the server in."
  type        = string
  default     = "us-east-1"

  validation {
    condition     = contains(["us-east-1", "us-west-2"], var.region)
    error_message = "Region must be one of: us-east-1, us-west-2."
  }
}

# -----------------------------------------------------------------------------
# Networking
# -----------------------------------------------------------------------------

variable "vpc_id" {
  description = "ID of the pre-existing VPC where the server will be deployed."
  type        = string
}

variable "subnet_id" {
  description = "ID of the subnet within the VPC for the server."
  type        = string
}

variable "vpc_cidr" {
  description = "CIDR block of the VPC. Used for security group rules."
  type        = string
}

variable "security_profile" {
  description = "Security profile for the server: web_facing, internal_only, database, custom."
  type        = string
  default     = "internal_only"
}

variable "custom_security_rules" {
  description = "Custom security group rules (only used when security_profile is 'custom')."
  type = list(object({
    type        = string
    from_port   = number
    to_port     = number
    protocol    = string
    cidr_blocks = list(string)
    description = string
  }))
  default = []
}

# -----------------------------------------------------------------------------
# Configuration
# -----------------------------------------------------------------------------

variable "domain_join" {
  description = "Whether to join the server to an Active Directory domain (Windows only)."
  type        = bool
  default     = false
}

variable "puppet_role" {
  description = "Puppet role to assign to the server (e.g., web_server, db_server, app_server, base)."
  type        = string
  default     = "base"
}

variable "key_name" {
  description = "SSH key pair name. Leave empty to rely on SSM only (recommended)."
  type        = string
  default     = ""
}

# -----------------------------------------------------------------------------
# Storage
# -----------------------------------------------------------------------------

variable "root_volume_size" {
  description = "Size of the root volume in GB. Set to 0 to use module defaults (30 for Linux, 50 for Windows)."
  type        = number
  default     = 0
}

variable "additional_storage" {
  description = "List of additional EBS volumes to attach to the server."
  type = list(object({
    device_name = string
    size_gb     = number
    volume_type = string
    tags        = map(string)
  }))
  default = []
}

# -----------------------------------------------------------------------------
# DNS
# -----------------------------------------------------------------------------

variable "route53_zone_id" {
  description = "Route53 hosted zone ID. If provided, a DNS A record will be created for the server."
  type        = string
  default     = ""
}

variable "dns_suffix" {
  description = "DNS suffix for the record (e.g., 'dev.internal.example.com'). Combined with server_name."
  type        = string
  default     = ""
}

# -----------------------------------------------------------------------------
# AMI Configuration
# -----------------------------------------------------------------------------

variable "ami_map" {
  description = "Map of OS type to AMI ID. Override to use custom or pre-baked AMIs."
  type        = map(string)
  default = {
    # Placeholder AMI IDs for us-east-1 -- replace with actual AMI IDs
    windows_2022      = "ami-0fc682b2a42e57ca2" # Windows Server 2022 Base
    windows_2019      = "ami-0c2b0d3fb02824d92" # Windows Server 2019 Base
    amazon_linux_2023 = "ami-0c101f26f147fa7fd" # Amazon Linux 2023
    ubuntu_2204       = "ami-0c7217cdde317cfec" # Ubuntu 22.04 LTS
    rhel_9            = "ami-0c0b74d29acd0cd97" # RHEL 9
  }
}

# -----------------------------------------------------------------------------
# Tags
# -----------------------------------------------------------------------------

variable "tags" {
  description = "Additional tags to apply to all resources created for this server."
  type        = map(string)
  default     = {}
}

# -----------------------------------------------------------------------------
# IAM
# -----------------------------------------------------------------------------

variable "custom_policy_arns" {
  description = "Additional IAM policy ARNs to attach to the server instance role."
  type        = list(string)
  default     = []
}
